#pragma once
#include "CoreMinimal.h"
#include "ETresEnemyStepDirectionType_e_ex358.generated.h"

UENUM(BlueprintType)
enum ETresEnemyStepDirectionType_e_ex358 {
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_RIGHT,
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_LEFT,
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_BACK,
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_FRONT,
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_AUTO,
    TRES_ENEMY_STEP_DIRECTION_TYPE_E_EX358_MAX UMETA(Hidden),
};

