#pragma once
#include "CoreMinimal.h"
#include "ETresEnemyRunDirectionType_e_ex358.generated.h"

UENUM(BlueprintType)
enum ETresEnemyRunDirectionType_e_ex358 {
    TRES_ENEMY_RUN_DIRECTION_TYPE_E_EX358_CAUTION_RIGHT,
    TRES_ENEMY_RUN_DIRECTION_TYPE_E_EX358_CAUTION_LEFT,
    TRES_ENEMY_RUN_DIRECTION_TYPE_E_EX358_CAUTION_VIEW_CENTER,
    TRES_ENEMY_RUN_DIRECTION_TYPE_E_EX358_TARGET,
    TRES_ENEMY_RUN_DIRECTION_TYPE_E_EX358_MAX UMETA(Hidden),
};

