#pragma once
#include "CoreMinimal.h"
#include "TresAttack4AscensionTypes_e_ex301.generated.h"

UENUM(BlueprintType)
enum TresAttack4AscensionTypes_e_ex301 {
    TRES_ATTACK4_ENEMY_EX301_ASCENSION1,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION2,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION3,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION4,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION5,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION6,
    TRES_ATTACK4_ENEMY_EX301_ASCENSION7,
    TRES_ATTACK4_ENEMY_EX301_MAX UMETA(Hidden),
};

