#pragma once
#include "CoreMinimal.h"
#include "DarkSplicerTypes_e_ex360.generated.h"

UENUM(BlueprintType)
enum DarkSplicerTypes_e_ex360 {
    TRES_ENEMY_EX360_DARKSPLICER_MOVE_CUTDOWN,
    TRES_ENEMY_EX360_DARKSPLICER_CUTDOWN,
    TRES_ENEMY_EX360_DARKSPLICER_CUTUP,
    TRES_ENEMY_EX360_DARKSPLICER_SPIN_CUTUP,
    TRES_ENEMY_EX360_DARKSPLICER_MOVE_WCUT,
    TRES_ENEMY_EX360_DARKSPLICER_WCUT,
    TRES_ENEMY_EX360_DARKSPLICER_MOVE_SPINCUT,
    TRES_ENEMY_EX360_DARKSPLICER_MAX UMETA(Hidden),
};

