// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "TresGameCheatManager.h"
#include "TresGumiShipCheatManager.generated.h"

/**
 * 
 */
UCLASS()
class TRESGAME_API UTresGumiShipCheatManager : public UTresGameCheatManager
{
	GENERATED_BODY()
public:
	void ToggleGumiShipEnemyStateNameVisibility() {};
	void ToggleGumiShipEnemyRespawnWaitStatusVisibility() {};
	void ToggleGumiShipEnemyBoundsSphereVisibility() {};
	void ToggleGumiShipEnemyAttackableCheckRaycastVisibility() {};
	void ShowDebugGumiShipLevelEntityActivateVolumeByTag(bool Visibility, const FName& TagName) {};
	void ShowDebugGumiShipLevelEntityActivateVolume(bool Visibility) {};
	void SetGumiShipEnemyMeshVisibility(const FName& EnemyID, bool Visibility) {};
	void SetGumiShipEnemyAttackableRangeVisibilityByName(const FName& EnemyID, const FName& AttackName, bool Visibility) {};
	void SetGumiShipEnemyAttackableRangeVisibility(const FName& EnemyID, bool Visibility) {};
	void SetGumiShipEnemyAttackableCheckRaycastDebugDrawTime(float DebugDrawSeconds) {};
	void SetGumiShipEnemyAttachEffectsVisibility(const FName& EnemyID, bool Visibility) {};
	void SetDebugGumiShipTriggerActorsVisibility(bool Visibility) {};
	void SendGumiShipEnemyDebugCommand(const FName& EnemyID, const FName& DebugCommandName) {};
	void GumiShipGimmick_Debug_HP_display() {};
	void GumiShipGimmick_Debug_ForcedTermination_TreasureSphere() {};
	void GumiShipGimmick_Debug_Cannon_Off() {};
	void GumiShip_Debug_SetGumiMissionProgressNum(int dIndex, int dParam) {};
	void GumiShip_Debug_ClearGumiMission(int dIndex) {};
	static class UTresGumiShipCheatManager* Get(class UObject* WorldContext) { return nullptr; };
	void DebugTresInstanceActorsCollisionEnable(bool bEnable) {};
	void DebugTreasureSphiaOpen(bool IsOpen) {};
	void DebugTravelPointOpen(bool IsOpen) {};
	void DebugSticker_SymbolFull() {};
	void DebugSticker_NumberFull() {};
	void DebugSticker_NatureFull() {};
	void DebugSticker_GUMISTICKER_ITEM075() {};
	void DebugSticker_GUMISTICKER_ITEM074() {};
	void DebugSticker_GUMISTICKER_ITEM073() {};
	void DebugSticker_GUMISTICKER_ITEM072() {};
	void DebugSticker_GUMISTICKER_ITEM071() {};
	void DebugSticker_GUMISTICKER_ITEM070() {};
	void DebugSticker_GUMISTICKER_ITEM069() {};
	void DebugSticker_GUMISTICKER_ITEM068() {};
	void DebugSticker_GUMISTICKER_ITEM067() {};
	void DebugSticker_GUMISTICKER_ITEM066() {};
	void DebugSticker_GUMISTICKER_ITEM065() {};
	void DebugSticker_GUMISTICKER_ITEM064() {};
	void DebugSticker_GUMISTICKER_ITEM063() {};
	void DebugSticker_GUMISTICKER_ITEM062() {};
	void DebugSticker_GUMISTICKER_ITEM061() {};
	void DebugSticker_GUMISTICKER_ITEM060() {};
	void DebugSticker_GUMISTICKER_ITEM059() {};
	void DebugSticker_GUMISTICKER_ITEM058() {};
	void DebugSticker_GUMISTICKER_ITEM057() {};
	void DebugSticker_GUMISTICKER_ITEM056() {};
	void DebugSticker_GUMISTICKER_ITEM055() {};
	void DebugSticker_GUMISTICKER_ITEM054() {};
	void DebugSticker_GUMISTICKER_ITEM053() {};
	void DebugSticker_GUMISTICKER_ITEM052() {};
	void DebugSticker_GUMISTICKER_ITEM051() {};
	void DebugSticker_GUMISTICKER_ITEM050() {};
	void DebugSticker_GUMISTICKER_ITEM049() {};
	void DebugSticker_GUMISTICKER_ITEM048() {};
	void DebugSticker_GUMISTICKER_ITEM047() {};
	void DebugSticker_GUMISTICKER_ITEM046() {};
	void DebugSticker_GUMISTICKER_ITEM045() {};
	void DebugSticker_GUMISTICKER_ITEM044() {};
	void DebugSticker_GUMISTICKER_ITEM043() {};
	void DebugSticker_GUMISTICKER_ITEM042() {};
	void DebugSticker_GUMISTICKER_ITEM041() {};
	void DebugSticker_GUMISTICKER_ITEM040() {};
	void DebugSticker_GUMISTICKER_ITEM039() {};
	void DebugSticker_GUMISTICKER_ITEM038() {};
	void DebugSticker_GUMISTICKER_ITEM037() {};
	void DebugSticker_GUMISTICKER_ITEM036() {};
	void DebugSticker_GUMISTICKER_ITEM035() {};
	void DebugSticker_GUMISTICKER_ITEM034() {};
	void DebugSticker_GUMISTICKER_ITEM033() {};
	void DebugSticker_GUMISTICKER_ITEM032() {};
	void DebugSticker_GUMISTICKER_ITEM031() {};
	void DebugSticker_GUMISTICKER_ITEM030() {};
	void DebugSticker_GUMISTICKER_ITEM029() {};
	void DebugSticker_GUMISTICKER_ITEM028() {};
	void DebugSticker_GUMISTICKER_ITEM027() {};
	void DebugSticker_GUMISTICKER_ITEM026() {};
	void DebugSticker_GUMISTICKER_ITEM025() {};
	void DebugSticker_GUMISTICKER_ITEM024() {};
	void DebugSticker_GUMISTICKER_ITEM023() {};
	void DebugSticker_GUMISTICKER_ITEM022() {};
	void DebugSticker_GUMISTICKER_ITEM021() {};
	void DebugSticker_GUMISTICKER_ITEM020() {};
	void DebugSticker_GUMISTICKER_ITEM019() {};
	void DebugSticker_GUMISTICKER_ITEM018() {};
	void DebugSticker_GUMISTICKER_ITEM017() {};
	void DebugSticker_GUMISTICKER_ITEM016() {};
	void DebugSticker_GUMISTICKER_ITEM015() {};
	void DebugSticker_GUMISTICKER_ITEM014() {};
	void DebugSticker_GUMISTICKER_ITEM013() {};
	void DebugSticker_GUMISTICKER_ITEM012() {};
	void DebugSticker_GUMISTICKER_ITEM011() {};
	void DebugSticker_GUMISTICKER_ITEM010() {};
	void DebugSticker_GUMISTICKER_ITEM009() {};
	void DebugSticker_GUMISTICKER_ITEM008() {};
	void DebugSticker_GUMISTICKER_ITEM007() {};
	void DebugSticker_GUMISTICKER_ITEM006() {};
	void DebugSticker_GUMISTICKER_ITEM005() {};
	void DebugSticker_GUMISTICKER_ITEM004() {};
	void DebugSticker_GUMISTICKER_ITEM003() {};
	void DebugSticker_GUMISTICKER_ITEM002() {};
	void DebugSticker_GUMISTICKER_ITEM001() {};
	void DebugSticker_EmblemFull() {};
	void DebugStaticMeshActorsCollisionEnable(bool bEnable) {};
	void DebugSpecialWeaponFull() {};
	void DebugSpecialWeapon_GUMIETC_ITEM060() {};
	void DebugSpecialWeapon_GUMIETC_ITEM059() {};
	void DebugSpecialWeapon_GUMIETC_ITEM058() {};
	void DebugSpecialWeapon_GUMIETC_ITEM055() {};
	void DebugSpecialWeapon_GUMIETC_ITEM053() {};
	void DebugSpecialWeapon_GUMIETC_ITEM052() {};
	void DebugSpecialWeapon_GUMIETC_ITEM049() {};
	void DebugSpecialWeapon_GUMIETC_ITEM048() {};
	void DebugSpecialWeapon_GUMIETC_ITEM047() {};
	void DebugSpecialWeapon_GUMIETC_ITEM046() {};
	void DebugSpecialWeapon_GUMIETC_ITEM045() {};
	void DebugSpecialWeapon_GUMIETC_ITEM044() {};
	void DebugSpecialWeapon_GUMIETC_ITEM043() {};
	void DebugSpecialPlanFull() {};
	void DebugRecommendedPlanFull() {};
	void DebugPvShootingMode(bool IsEnable) {};
	void DebugPatternSymbolFull() {};
	void DebugPatternOrientalFull() {};
	void DebugPatternCutelFull() {};
	void DebugPatternBasicFull() {};
	void DebugPatternArtFull() {};
	void DebugPattern_No96() {};
	void DebugPattern_No95() {};
	void DebugPattern_No94() {};
	void DebugPattern_No93() {};
	void DebugPattern_No92() {};
	void DebugPattern_No91() {};
	void DebugPattern_No90() {};
	void DebugPattern_No9() {};
	void DebugPattern_No89() {};
	void DebugPattern_No88() {};
	void DebugPattern_No87() {};
	void DebugPattern_No86() {};
	void DebugPattern_No85() {};
	void DebugPattern_No84() {};
	void DebugPattern_No83() {};
	void DebugPattern_No82() {};
	void DebugPattern_No81() {};
	void DebugPattern_No80() {};
	void DebugPattern_No8() {};
	void DebugPattern_No79() {};
	void DebugPattern_No78() {};
	void DebugPattern_No77() {};
	void DebugPattern_No76() {};
	void DebugPattern_No75() {};
	void DebugPattern_No74() {};
	void DebugPattern_No73() {};
	void DebugPattern_No72() {};
	void DebugPattern_No71() {};
	void DebugPattern_No70() {};
	void DebugPattern_No7() {};
	void DebugPattern_No69() {};
	void DebugPattern_No68() {};
	void DebugPattern_No67() {};
	void DebugPattern_No66() {};
	void DebugPattern_No65() {};
	void DebugPattern_No64() {};
	void DebugPattern_No63() {};
	void DebugPattern_No62() {};
	void DebugPattern_No61() {};
	void DebugPattern_No60() {};
	void DebugPattern_No6() {};
	void DebugPattern_No59() {};
	void DebugPattern_No58() {};
	void DebugPattern_No57() {};
	void DebugPattern_No56() {};
	void DebugPattern_No55() {};
	void DebugPattern_No54() {};
	void DebugPattern_No53() {};
	void DebugPattern_No52() {};
	void DebugPattern_No51() {};
	void DebugPattern_No50() {};
	void DebugPattern_No5() {};
	void DebugPattern_No49() {};
	void DebugPattern_No48() {};
	void DebugPattern_No47() {};
	void DebugPattern_No46() {};
	void DebugPattern_No45() {};
	void DebugPattern_No44() {};
	void DebugPattern_No43() {};
	void DebugPattern_No42() {};
	void DebugPattern_No41() {};
	void DebugPattern_No40() {};
	void DebugPattern_No4() {};
	void DebugPattern_No39() {};
	void DebugPattern_No38() {};
	void DebugPattern_No37() {};
	void DebugPattern_No36() {};
	void DebugPattern_No35() {};
	void DebugPattern_No34() {};
	void DebugPattern_No33() {};
	void DebugPattern_No32() {};
	void DebugPattern_No31() {};
	void DebugPattern_No30() {};
	void DebugPattern_No3() {};
	void DebugPattern_No29() {};
	void DebugPattern_No28() {};
	void DebugPattern_No27() {};
	void DebugPattern_No26() {};
	void DebugPattern_No25() {};
	void DebugPattern_No24() {};
	void DebugPattern_No23() {};
	void DebugPattern_No22() {};
	void DebugPattern_No21() {};
	void DebugPattern_No20() {};
	void DebugPattern_No2() {};
	void DebugPattern_No19() {};
	void DebugPattern_No18() {};
	void DebugPattern_No17() {};
	void DebugPattern_No16() {};
	void DebugPattern_No15() {};
	void DebugPattern_No14() {};
	void DebugPattern_No13() {};
	void DebugPattern_No12() {};
	void DebugPattern_No11() {};
	void DebugPattern_No10() {};
	void DebugPattern_No1() {};
	void DebugPattern_No0() {};
	void DebugMaterialNature() {};
	void DebugMaterialHandcraft() {};
	void DebugMaterialEarth() {};
	void DebugMaterialBasicFull() {};
	void DebugMaterial_No9() {};
	void DebugMaterial_No8() {};
	void DebugMaterial_No7() {};
	void DebugMaterial_No6() {};
	void DebugMaterial_No57() {};
	void DebugMaterial_No56() {};
	void DebugMaterial_No55() {};
	void DebugMaterial_No54() {};
	void DebugMaterial_No53() {};
	void DebugMaterial_No52() {};
	void DebugMaterial_No51() {};
	void DebugMaterial_No50() {};
	void DebugMaterial_No5() {};
	void DebugMaterial_No49() {};
	void DebugMaterial_No48() {};
	void DebugMaterial_No47() {};
	void DebugMaterial_No46() {};
	void DebugMaterial_No45() {};
	void DebugMaterial_No44() {};
	void DebugMaterial_No43() {};
	void DebugMaterial_No42() {};
	void DebugMaterial_No41() {};
	void DebugMaterial_No40() {};
	void DebugMaterial_No4() {};
	void DebugMaterial_No39() {};
	void DebugMaterial_No38() {};
	void DebugMaterial_No37() {};
	void DebugMaterial_No36() {};
	void DebugMaterial_No35() {};
	void DebugMaterial_No34() {};
	void DebugMaterial_No33() {};
	void DebugMaterial_No32() {};
	void DebugMaterial_No31() {};
	void DebugMaterial_No30() {};
	void DebugMaterial_No3() {};
	void DebugMaterial_No29() {};
	void DebugMaterial_No28() {};
	void DebugMaterial_No27() {};
	void DebugMaterial_No26() {};
	void DebugMaterial_No25() {};
	void DebugMaterial_No24() {};
	void DebugMaterial_No23() {};
	void DebugMaterial_No22() {};
	void DebugMaterial_No21() {};
	void DebugMaterial_No20() {};
	void DebugMaterial_No2() {};
	void DebugMaterial_No19() {};
	void DebugMaterial_No18() {};
	void DebugMaterial_No17() {};
	void DebugMaterial_No16() {};
	void DebugMaterial_No15() {};
	void DebugMaterial_No14() {};
	void DebugMaterial_No13() {};
	void DebugMaterial_No12() {};
	void DebugMaterial_No11() {};
	void DebugMaterial_No10() {};
	void DebugMaterial_No1() {};
	void DebugMaterial_No0() {};
	void DebugJumpPointOpen(bool IsOpen) {};
	void DebugGummiShipCaptureEnable(bool IsEnable) {};
	void DebugGummiShipAngleZ(int inAngleZ) {};
	void DebugGummiShipAngleX(int inAngleX) {};
	void DebugGummiPlan_ITEM122() {};
	void DebugGummiPlan_ITEM121() {};
	void DebugGummiPlan_ITEM120() {};
	void DebugGummiPlan_ITEM119() {};
	void DebugGummiPlan_ITEM118() {};
	void DebugGummiPlan_ITEM117() {};
	void DebugGummiPlan_ITEM116() {};
	void DebugGummiPlan_ITEM115() {};
	void DebugGummiPlan_ITEM114() {};
	void DebugGummiPlan_ITEM113() {};
	void DebugGummiPlan_ITEM112() {};
	void DebugGummiPlan_ITEM111() {};
	void DebugGummiPlan_ITEM110() {};
	void DebugGummiPlan_ITEM109() {};
	void DebugGummiPlan_ITEM108() {};
	void DebugGummiPlan_ITEM107() {};
	void DebugGummiPlan_ITEM106() {};
	void DebugGummiPlan_ITEM105() {};
	void DebugGummiPlan_ITEM104() {};
	void DebugGummiPlan_ITEM103() {};
	void DebugGummiPlan_ITEM102() {};
	void DebugGummiPlan_ITEM101() {};
	void DebugGummiPlan_ITEM100() {};
	void DebugGummiPlan_ITEM099() {};
	void DebugGummiPlan_ITEM098() {};
	void DebugGummiPlan_ITEM097() {};
	void DebugGummiPlan_ITEM096() {};
	void DebugGummiPlan_ITEM095() {};
	void DebugGummiPlan_ITEM094() {};
	void DebugGummiPlan_ITEM093() {};
	void DebugGummiPlan_ITEM092() {};
	void DebugGummiPlan_ITEM091() {};
	void DebugGummiPlan_ITEM090() {};
	void DebugGummiPlan_ITEM089() {};
	void DebugGummiPlan_ITEM088() {};
	void DebugGummiPlan_ITEM087() {};
	void DebugGummiPlan_ITEM086() {};
	void DebugGummiPlan_ITEM085() {};
	void DebugGummiPlan_ITEM084() {};
	void DebugGummiPlan_ITEM083() {};
	void DebugGummiPlan_ITEM067() {};
	void DebugGummiPlan_ITEM066() {};
	void DebugGummiPlan_ITEM065() {};
	void DebugGummiPlan_ITEM064() {};
	void DebugGummiPlan_ITEM063() {};
	void DebugGummiPlan_ITEM062() {};
	void DebugGummiPlan_ITEM061() {};
	void DebugGummiPlan_ITEM060() {};
	void DebugGummiPlan_ITEM059() {};
	void DebugGummiPlan_ITEM058() {};
	void DebugGummiPlan_ITEM057() {};
	void DebugGummiPlan_ITEM056() {};
	void DebugGummiLvel(uint32_t InLevel) {};
	void DebugGummiItemFull() {};
	void DebugGumiShipWorldGuideAllEnable(bool IsOn) {};
	void DebugGumiShipTutorialSkip() {};
	void DebugGumiShipToggleMergeMesh(bool flg) {};
	void DebugGumiShipSetRecordRank(int dIndex, int dParam) {};
	void DebugGumiShipSetRailCollisionDisable() {};
	void DebugGumiShipSetGimmickFlag(uint32_t udFlag, bool bIn) {};
	void DebugGumiShipSetDrawDamageInfo(bool bIn) {};
	void DebugGumiShipSetBGCollisionEnable(bool bIn) {};
	void DebugGumiShipLevelEntityActivateVolumeEnable(bool bEnable) {};
	void DebugGumiShipHudSuppression(bool IsOn) {};
	void DebugGumiShipEnemyTakeDamageZero(bool bEnable) {};
	void DebugGumiShipEnemyPartsHitPointVisibility(bool bVisibility) {};
	void DebugGumiShipEnemyPartsDestroyOnDamage(bool bEnable) {};
	void DebugGumiShipEnemyHPGaugeIgnore(bool IsOn) {};
	void DebugGumiShipEnemyHPGaugeEnable(bool IsOn) {};
	void DebugGumiShipEnemyHitPointVisibility(bool bVisibility) {};
	void DebugGumiShipEnemyBattleStartTriggerIgnore(bool bIgnoreFlag) {};
	void DebugGumiShipClusterActorsCollisionEnable(bool bEnable) {};
	void DebugGumiShipBattleMissionSetTotalScore(uint32_t udScore) {};
	void DebugGumiShipBattleMissionForceSearchRestart() {};
	void DebugGumiShipBattleMissionForceRetry() {};
	void DebugGumiShipBattleMissionForceQuit() {};
	void DebugGumiShipBattleMissionDrawInfo(bool bIn) {};
	void DebugGumiShipAllRecordRankA() {};
	void DebugGoWorldMap() {};
	void DebugGetTreasureMap() {};
	void DebugFullEquipAndMaxLevel() {};
	void DebugForceGumiShipEnemyRespawn() {};
	void DebugForceChangeSchwarzGeistBGM(int nChangeBgmMagicNumber) {};
	void DebugExpPrize(uint32_t inPrize) {};
	void DebugEditGummiShipSkeletalMeshTickEnable(bool bEnable) {};
	void DebugArenaVisited(bool isVisit) {};
	void DebugAddWingGummi_index09() {};
	void DebugAddWingGummi_index08() {};
	void DebugAddWingGummi_index07() {};
	void DebugAddWingGummi_index06() {};
	void DebugAddWingGummi_index05() {};
	void DebugAddWingGummi_index04() {};
	void DebugAddWingGummi_index03() {};
	void DebugAddWingGummi_index02() {};
	void DebugAddWingGummi_index01() {};
	void DebugAddWingGummi_index00() {};
	void DebugAddWheelGummi_index02() {};
	void DebugAddWheelGummi_index01() {};
	void DebugAddWheelGummi_index00() {};
	void DebugAddStrikeGummi_index11() {};
	void DebugAddStrikeGummi_index10() {};
	void DebugAddStrikeGummi_index09() {};
	void DebugAddStrikeGummi_index08() {};
	void DebugAddStrikeGummi_index07() {};
	void DebugAddStrikeGummi_index06() {};
	void DebugAddStrikeGummi_index05() {};
	void DebugAddStrikeGummi_index04() {};
	void DebugAddStrikeGummi_index03() {};
	void DebugAddStrikeGummi_index02() {};
	void DebugAddStrikeGummi_index01() {};
	void DebugAddStrikeGummi_index00() {};
	void DebugAddShootingGummi_index17() {};
	void DebugAddShootingGummi_index16() {};
	void DebugAddShootingGummi_index11() {};
	void DebugAddShootingGummi_index10() {};
	void DebugAddShootingGummi_index09() {};
	void DebugAddShootingGummi_index08() {};
	void DebugAddShootingGummi_index07() {};
	void DebugAddShootingGummi_index06() {};
	void DebugAddShootingGummi_index05() {};
	void DebugAddShootingGummi_index04() {};
	void DebugAddShootingGummi_index03() {};
	void DebugAddShootingGummi_index02() {};
	void DebugAddShootingGummi_index01() {};
	void DebugAddShootingGummi_index00() {};
	void DebugAddShieldGummi_index03() {};
	void DebugAddShieldGummi_index02() {};
	void DebugAddShieldGummi_index01() {};
	void DebugAddShieldGummi_index00() {};
	void DebugAddPipeGummi_09() {};
	void DebugAddPipeGummi_08() {};
	void DebugAddPipeGummi_07() {};
	void DebugAddPipeGummi_06() {};
	void DebugAddPipeGummi_05() {};
	void DebugAddPipeGummi_04() {};
	void DebugAddPipeGummi_03() {};
	void DebugAddPipeGummi_02() {};
	void DebugAddPipeGummi_01() {};
	void DebugAddOptionGummi_index15() {};
	void DebugAddOptionGummi_index14() {};
	void DebugAddOptionGummi_index13() {};
	void DebugAddOptionGummi_index12() {};
	void DebugAddOptionGummi_index11() {};
	void DebugAddOptionGummi_index10() {};
	void DebugAddOptionGummi_index09() {};
	void DebugAddOptionGummi_index08() {};
	void DebugAddOptionGummi_index07() {};
	void DebugAddOptionGummi_index06() {};
	void DebugAddOptionGummi_index05() {};
	void DebugAddOptionGummi_index04() {};
	void DebugAddOptionGummi_index03() {};
	void DebugAddOptionGummi_index02() {};
	void DebugAddOptionGummi_index01() {};
	void DebugAddOptionGummi_index00() {};
	void DebugAddLaserGummi_index05() {};
	void DebugAddLaserGummi_index04() {};
	void DebugAddLaserGummi_index03() {};
	void DebugAddLaserGummi_index02() {};
	void DebugAddEngineGummi_index10() {};
	void DebugAddEngineGummi_index09() {};
	void DebugAddEngineGummi_index08() {};
	void DebugAddEngineGummi_index07() {};
	void DebugAddEngineGummi_index06() {};
	void DebugAddEngineGummi_index05() {};
	void DebugAddEngineGummi_index04() {};
	void DebugAddEngineGummi_index03() {};
	void DebugAddEngineGummi_index02() {};
	void DebugAddEngineGummi_index01() {};
	void DebugAddEngineGummi_index00() {};
	void DebugAddEdgeGummi_13() {};
	void DebugAddEdgeGummi_12() {};
	void DebugAddEdgeGummi_11() {};
	void DebugAddEdgeGummi_09() {};
	void DebugAddEdgeGummi_08() {};
	void DebugAddEdgeGummi_07() {};
	void DebugAddEdgeGummi_06() {};
	void DebugAddEdgeGummi_05() {};
	void DebugAddEdgeGummi_04() {};
	void DebugAddEdgeGummi_03() {};
	void DebugAddEdgeGummi_02() {};
	void DebugAddEdgeGummi_01() {};
	void DebugAddCurveGummi_16() {};
	void DebugAddCurveGummi_15() {};
	void DebugAddCurveGummi_14() {};
	void DebugAddCurveGummi_13() {};
	void DebugAddCurveGummi_12() {};
	void DebugAddCurveGummi_11() {};
	void DebugAddCurveGummi_09() {};
	void DebugAddCurveGummi_08() {};
	void DebugAddCurveGummi_07() {};
	void DebugAddCurveGummi_06() {};
	void DebugAddCurveGummi_05() {};
	void DebugAddCurveGummi_04() {};
	void DebugAddCurveGummi_03() {};
	void DebugAddCurveGummi_02() {};
	void DebugAddCurveGummi_01() {};
	void DebugAddCockpitGummi_index07() {};
	void DebugAddCockpitGummi_index06() {};
	void DebugAddCockpitGummi_index05() {};
	void DebugAddCockpitGummi_index04() {};
	void DebugAddCockpitGummi_index03() {};
	void DebugAddCockpitGummi_index02() {};
	void DebugAddCockpitGummi_index01() {};
	void DebugAddCockpitGummi_index00() {};
	void DebugAddCharacterGummi_index13() {};
	void DebugAddCharacterGummi_index12() {};
	void DebugAddCharacterGummi_index11() {};
	void DebugAddCharacterGummi_index10() {};
	void DebugAddCharacterGummi_index09() {};
	void DebugAddCharacterGummi_index08() {};
	void DebugAddCharacterGummi_index07() {};
	void DebugAddCharacterGummi_index06() {};
	void DebugAddCharacterGummi_index05() {};
	void DebugAddCharacterGummi_index04() {};
	void DebugAddCharacterGummi_index03() {};
	void DebugAddCharacterGummi_index02() {};
	void DebugAddCharacterGummi_index01() {};
	void DebugAddCharacterGummi_index00() {};
	void DebugAddAeroGummi_13() {};
	void DebugAddAeroGummi_12() {};
	void DebugAddAeroGummi_11() {};
	void DebugAddAeroGummi_09() {};
	void DebugAddAeroGummi_08() {};
	void DebugAddAeroGummi_07() {};
	void DebugAddAeroGummi_06() {};
	void DebugAddAeroGummi_05() {};
	void DebugAddAeroGummi_04() {};
	void DebugAddAeroGummi_03() {};
	void DebugAddAeroGummi_02() {};
	void DebugAddAeroGummi_01() {};
};
