#pragma once
#include "CoreMinimal.h"
#include "TresGimmickHitCountComponentOnTresAccumulationRecoveryedSignatureDelegate.generated.h"

UDELEGATE() DECLARE_DYNAMIC_MULTICAST_DELEGATE(FTresGimmickHitCountComponentOnTresAccumulationRecoveryedSignature);

