#pragma once
#include "CoreMinimal.h"
#include "EQS_PARAM_NAME_Enum.generated.h"

UENUM(BlueprintType)
enum class EQS_PARAM_NAME_Enum : uint8 {
    ONRING_MINRADIUS,
    ONRING_MAXRADIUS,
    ONRING_MINRADIUSITEMSPACING,
    ONRING_ANGLE,
    EQ_PAWNDISTANCE,
    RANGE,
    MINDISTANCE_FLOATVALUEMIN,
    MINDISTANCE_FLOATVALUEMAX,
    DOT_SCORINGFACTOR,
    DOT_SCORINGFACTOR2,
    NOISE_SCORINGFACTOR,
    EQS_PARAM_NAME_MAX UMETA(Hidden),
};

