#pragma once
#include "CoreMinimal.h"
#include "ETresWeaponForm.generated.h"

UENUM(BlueprintType)
enum class ETresWeaponForm : uint8 {
    TRES_WEAPON_FORM_NONE,
    TRES_WEAPON_FORM_01,
    TRES_WEAPON_FORM_02,
    TRES_WEAPON_FORM_03,
    TRES_WEAPON_FORM_04,
    TRES_WEAPON_FORM_05,
    TRES_WEAPON_FORM_06,
    TRES_WEAPON_FORM_07,
    TRES_WEAPON_FORM_08,
    TRES_WEAPON_FORM_09,
    TRES_WEAPON_FORM_0A,
    TRES_WEAPON_FORM_0B,
    TRES_WEAPON_FORM_0C,
    TRES_WEAPON_FORM_0D,
    TRES_WEAPON_FORM_0E,
    TRES_WEAPON_FORM_0F,
    TRES_WEAPON_FORM_10,
    TRES_WEAPON_FORM_11,
    TRES_WEAPON_FORM_12,
    TRES_WEAPON_FORM_13,
    TRES_WEAPON_FORM_14,
    TRES_WEAPON_FORM_15,
    TRES_WEAPON_FORM_16,
    TRES_WEAPON_FORM_17,
    TRES_WEAPON_FORM_18,
    TRES_WEAPON_FORM_MAX UMETA(Hidden),
};

