#pragma once
#include "CoreMinimal.h"
#include "ETresEffectCustomAreaCode.generated.h"

UENUM(BlueprintType)
enum ETresEffectCustomAreaCode {
    TRES_EFFECT_CUSTOM_AREA_100 = 0x64,
    TRES_EFFECT_CUSTOM_AREA_101,
    TRES_EFFECT_CUSTOM_AREA_102,
    TRES_EFFECT_CUSTOM_AREA_103,
    TRES_EFFECT_CUSTOM_AREA_104,
    TRES_EFFECT_CUSTOM_AREA_105,
    TRES_EFFECT_CUSTOM_AREA_106,
    TRES_EFFECT_CUSTOM_AREA_107,
    TRES_EFFECT_CUSTOM_AREA_108,
    TRES_EFFECT_CUSTOM_AREA_109,
    TRES_EFFECT_CUSTOM_AREA_110,
    TRES_EFFECT_CUSTOM_AREA_111,
    TRES_EFFECT_CUSTOM_AREA_112,
    TRES_EFFECT_CUSTOM_AREA_113,
    TRES_EFFECT_CUSTOM_AREA_114,
    TRES_EFFECT_CUSTOM_AREA_115,
    TRES_EFFECT_CUSTOM_AREA_116,
    TRES_EFFECT_CUSTOM_AREA_117,
    TRES_EFFECT_CUSTOM_AREA_118,
    TRES_EFFECT_CUSTOM_AREA_119,
    TRES_EFFECT_CUSTOM_AREA_120,
    TRES_EFFECT_CUSTOM_AREA_121,
    TRES_EFFECT_CUSTOM_AREA_122,
    TRES_EFFECT_CUSTOM_AREA_123,
    TRES_EFFECT_CUSTOM_AREA_124,
    TRES_EFFECT_CUSTOM_AREA_125,
    TRES_EFFECT_CUSTOM_AREA_126,
    TRES_EFFECT_CUSTOM_AREA_127,
    TRES_EFFECT_CUSTOM_AREA_128,
    TRES_EFFECT_CUSTOM_AREA_129,
    TRES_EFFECT_CUSTOM_AREA_130,
    TRES_EFFECT_CUSTOM_AREA_MAX UMETA(Hidden),
};

