#pragma once
#include "CoreMinimal.h"
#include "ETresAbilityKind.generated.h"

UENUM(BlueprintType)
enum class ETresAbilityKind : uint8 {
    NONE = 0 UMETA(DisplayName = "None"),
	AIR_RECOVERY = 1 UMETA(DisplayName = "Aerial Recovery"),
	BLOW_COUNTER = 2 UMETA(DisplayName = "Payback Strike"),
	REFLECT_GUARD = 3 UMETA(DisplayName = "Block"),
	GUARD_COUNTER = 4 UMETA(DisplayName = "Counter Slash"),
	REVENGEIMPACT = 5 UMETA(DisplayName = "Counter Impact"),
	REVENGEDIVE = 6 UMETA(DisplayName = "Counter Kick"),
	REVENGE_EX = 7 UMETA(DisplayName = "Counter Blast"),
	RISKDODGE = 8 UMETA(DisplayName = "Risk Dodge"),
	RD_COUNTER = 9 UMETA(DisplayName = "RD Counter"),
	SLASH_UPPER = 10 UMETA(DisplayName = "Rising Spiral"),
	AIR_ROLL_BEAT = 11 UMETA(DisplayName = "Groundbreaker"),
	AIR_DOWN = 12 UMETA(DisplayName = "Falling Slash"),
	TRIPPLE_SLASH = 13 UMETA(DisplayName = "Triple Rush"),
	CHARGE_THRUST = 14 UMETA(DisplayName = "Speed Slash"),
	MAGICFLUSH = 15 UMETA(DisplayName = "Magic Flash"),
	HIGHJUMP = 16 UMETA(DisplayName = "High Jump"),
	DOUBLEFLIGHT = 17 UMETA(DisplayName = "Doubleflight"),
	SUPERJUMP = 18 UMETA(DisplayName = "Superjump"),
	SUPERSLIDE = 19 UMETA(DisplayName = "Superslide"),
	GLIDE = 20 UMETA(DisplayName = "Glide"),
	LIBRA = 21 UMETA(DisplayName = "Scan"),
	DODGE = 22 UMETA(DisplayName = "Dodge Roll"),
	AIRSLIDE = 23 UMETA(DisplayName = "Air Slide"),
	AIRDODGE = 24 UMETA(DisplayName = "Aerial Dodge"),
	MP_SAFETY = 25 UMETA(DisplayName = "MP Safety"),
	EXPZERO = 26 UMETA(DisplayName = "Zero EXP"),
	FRIEND_AID = 27 UMETA(DisplayName = "Assist Friends"),
	COMBO_PLUS = 28 UMETA(DisplayName = "Combo Plus"),
	AIRCOMBO_PLUS = 29 UMETA(DisplayName = "Air Combo Plus"),
	COMBO_MASTER = 30 UMETA(DisplayName = "Combo Master"),
	COMBO_UP = 31 UMETA(DisplayName = "Combo Boost"),
	AIRCOMBO_UP = 32 UMETA(DisplayName = "Air Combo Boost"),
	FIRE_UP = 33 UMETA(DisplayName = "Fire Boost"),
	BLIZZARD_UP = 34 UMETA(DisplayName = "Blizzard Boost"),
	THUNDER_UP = 35 UMETA(DisplayName = "Thunder Boost"),
	WATER_UP = 36 UMETA(DisplayName = "Water Boost"),
	AERO_UP = 37 UMETA(DisplayName = "Aero Boost"),
	WIZZARD_STAR = 38 UMETA(DisplayName = "Wizard's Ruse"),
	LUCK_UP = 39 UMETA(DisplayName = "Lucky Strike"),
	ITEM_UP = 40 UMETA(DisplayName = "Item Boost"),
	PRIZE_DRAW = 41 UMETA(DisplayName = "Treasure Magnet"),
	FOCUS_BOOST = 42 UMETA(DisplayName = "Focus Converter"),
	LEAF_VEIL = 43 UMETA(DisplayName = "Leaf Bracer"),
	LAST_LEAVE = 44 UMETA(DisplayName = "Second Chance"),
	COMBO_LEAVE = 45 UMETA(DisplayName = "Withstand Combo"),
	FOCUS_ASPIR = 46 UMETA(DisplayName = "Focus Syphon"),
	ATTRACTION_TIME = 47 UMETA(DisplayName = "Attraction Extender"),
	LINK_BOOST = 48 UMETA(DisplayName = "Link Extender"),
	FORM_TIME = 49 UMETA(DisplayName = "Formchange Extender"),
	DEFENDER = 50 UMETA(DisplayName = "Defender"),
	CRITICAL_HALF = 51 UMETA(DisplayName = "Damage Control"),
	DAMAGE_ASPIR = 52 UMETA(DisplayName = "Damage Syphon"),
	MP_HASTE = 53 UMETA(DisplayName = "MP Haste"),
	MP_HASTERA = 54 UMETA(DisplayName = "MP Hastera"),
	MP_HASTEGA = 55 UMETA(DisplayName = "MP Hastega"),
	MAGIC_COMBO_SAVE = 56 UMETA(DisplayName = "Magic Combo Thrift"),
	MAGIC_COMBO_UP = 57 UMETA(DisplayName = "Magic Galvanizer"),
	WALK_REGENE = 58 UMETA(DisplayName = "MP Walker"),
	WALK_HEALING = 59 UMETA(DisplayName = "HP Walker"),
	MAGIC_DRAW = 60 UMETA(DisplayName = "Magic Treasure Magnet"),
	MASTER_DRAW = 61 UMETA(DisplayName = "Master Treasure Magnet"),
	ATTRACTION_UP = 62 UMETA(DisplayName = "Attraction Enhancer"),
	BURN_GUARD = 63 UMETA(DisplayName = "Burn Guard"),
	CLOUD_GUARD = 64 UMETA(DisplayName = "Cloud Guard"),
	SNEEZE_GUARD = 65 UMETA(DisplayName = "Sneeze Guard"),
	FREEZE_GUARD = 66 UMETA(DisplayName = "Freeze Guard"),
	DISCHARGE_GUARD = 67 UMETA(DisplayName = "Electric Guard"),
	STUN_GUARD = 68 UMETA(DisplayName = "Stun Guard"),
	COUNTER_UP = 69 UMETA(DisplayName = "Reprisal Boost"),
	AUTO_FINISH = 70 UMETA(DisplayName = "Auto-Finish"),
	FORM_UP = 71 UMETA(DisplayName = "Situation Boost"),
	MAGIC_TIME = 72 UMETA(DisplayName = "Grand Magic Extender"),
	AUTO_LOCK_MAGIC = 73 UMETA(DisplayName = "Magic Lock-On"),
	GUARD_REGENE = 74 UMETA(DisplayName = "Block Replenisher"),
	MP_SAVE = 75 UMETA(DisplayName = "MP Thrift"),
	MP_LEAVE = 76 UMETA(DisplayName = "Extra Cast"),
	FULLMP_BURST = 77 UMETA(DisplayName = "Full MP Blast"),
	HARVEST = 78 UMETA(DisplayName = "Harvester"),
	HP_CONVERTER = 79 UMETA(DisplayName = "HP Converter"),
	MP_CONVERTER = 80 UMETA(DisplayName = "MP Converter"),
	MUNNY_CONVERTER = 81 UMETA(DisplayName = "Munny Converter"),
	ENDLESS_MAGIC = 82 UMETA(DisplayName = "Endless Magic"),
	FP_CONVERTER = 83 UMETA(DisplayName = "Focus Converter"),
	FIRE_ASPIR = 84 UMETA(DisplayName = "Fire Syphon"),
	BLIZZARD_ASPIR = 85 UMETA(DisplayName = "Blizzard Syphon"),
	THUNDER_ASPIR = 86 UMETA(DisplayName = "Thunder Syphon"),
	WATER_ASPIR = 87 UMETA(DisplayName = "Water Syphon"),
	AERO_ASPIR = 88 UMETA(DisplayName = "Aero Syphon"),
	DARK_ASPIR = 89 UMETA(DisplayName = "Dark Syphon"),
	BEST_COMBI = 90 UMETA(DisplayName = "Team Effort"),
	SONIC_SLASH = 91 UMETA(DisplayName = "Sonic Slash"),
	SONIC_DOWN = 92 UMETA(DisplayName = "Sonic Cleave"),
	TURN_CUTTER = 93 UMETA(DisplayName = "Buzz Saw"),
	SUMMERSALT = 94 UMETA(DisplayName = "Somersault"),
	POLE_SPIN = 95 UMETA(DisplayName = "Pole Spin"),
	POLE_SWING = 96 UMETA(DisplayName = "Pole Swing"),
	WALL_KICK = 97 UMETA(DisplayName = "Wall Kick"),
	BATTLE_GRAPHER = 98 UMETA(DisplayName = "Frontline Photographer"),
	CHARISMA_CHEF = 99 UMETA(DisplayName = "Chef Extraordinaire"),
	JOIN_FORCE = 100 UMETA(DisplayName = "Double Team"),
	HEARTLESS_BUSTER = 101 UMETA(DisplayName = "Heartless Buster"),
	NOBODY_BUSTER = 102 UMETA(DisplayName = "Nobody Buster"),
	POWER_CURE = 103 UMETA(DisplayName = "Cure Converter"),
	CRITICAL_COUNTER = 104 UMETA(DisplayName = "Critical Counter"),
	CRITICAL_CHARGE = 105 UMETA(DisplayName = "Critical Charge"),
	CRITICAL_CONVERTER = 106 UMETA(DisplayName = "Critical Converter"),
	QUICK_SHAFT = 107 UMETA(DisplayName = "Quick Slash"),
	FLASH_STEP = 108 UMETA(DisplayName = "Flash Step"),
	RADIAL_CUT = 109 UMETA(DisplayName = "Radial Blaster"),
	FINAL_HEAVEN = 110 UMETA(DisplayName = "Last Charge"),
	AERIAL_SWEEP = 111 UMETA(DisplayName = "Aerial Sweep"),
	AERIAL_DIVE = 112 UMETA(DisplayName = "Aerial Dive"),
	LUNCH_TIME = 113 UMETA(DisplayName = "Cuisine Extender"),
	POWER_LUNCH = 114 UMETA(DisplayName = "Hearty Meal"),
	OVER_TIME = 115 UMETA(DisplayName = "Overtime"),
	BEST_CONDITION = 116 UMETA(DisplayName = "Top Condition"),
	EXP_BARGAIN = 117 UMETA(DisplayName = "EXP Incentive"),
	PRIZE_FEEVER = 118 UMETA(DisplayName = "Prize Proliferator"),
	MILLIONAIRE = 119 UMETA(DisplayName = "Rags to Riches"),
	CURAGAN = 120 UMETA(DisplayName = "Curaza"),
	CHARGE_BERSERK = 121 UMETA(DisplayName = "Berserk Charge"),
	OVERCOME = 122 UMETA(DisplayName = "Hidden Potential"),
	GRAND_MAGIC = 123 UMETA(DisplayName = "More Grand Magic"),
	FIRAGAN = 124 UMETA(DisplayName = "Firaza"),
	BLIZZAGAN = 125 UMETA(DisplayName = "Blizzaza"),
	THUNDAGAN = 126 UMETA(DisplayName = "Thundaza"),
	WATAGAN = 127 UMETA(DisplayName = "Wataza"),
	AEROGAN = 128 UMETA(DisplayName = "Aeroza"),
	MAGIC_ROULETTE = 129 UMETA(DisplayName = "Magic Roulette"),
	UNISON_FIRE = 130 UMETA(DisplayName = "Unison Fire"),
	UNISON_BLIZZARD = 131 UMETA(DisplayName = "Unison Blizzard"),
	UNISON_THUNDER = 132 UMETA(DisplayName = "Unison Thunder"),
	FUSION_SPIN = 133 UMETA(DisplayName = "Fusion Spin"),
	FUSION_ROCKET = 134 UMETA(DisplayName = "Fusion Rocket"),
	HYPER_HEALING = 135 UMETA(DisplayName = "Hyper Healing"),
	COMBI_UP = 136 UMETA(DisplayName = "More Team Attacks"),
	COMBI_TIME = 137 UMETA(DisplayName = "Team Attack Extender"),
	SHARE_PRIZE = 138 UMETA(DisplayName = "Share Prizes"),
	MICKEY_CURE = 139 UMETA(DisplayName = "Mickey Cure"),
	MICKEY_HOLY = 140 UMETA(DisplayName = "Mickey Holy"),
	DONALD_FIRE = 141 UMETA(DisplayName = "Donald Fire"),
	DONALD_BLIZZARD = 142 UMETA(DisplayName = "Donald Blizzard"),
	DONALD_THUNDER = 143 UMETA(DisplayName = "Donald Thunder"),
	DONALD_AERO = 144 UMETA(DisplayName = "Donald Aero"),
	DONALD_CURE = 145 UMETA(DisplayName = "Donald Cure"),
	GOOFY_TORNADE = 146 UMETA(DisplayName = "Goofy Tornade"),
	GOOFY_TURBO = 147 UMETA(DisplayName = "Goofy Turbo"),
	GOOFY_FLIP = 148 UMETA(DisplayName = "Goofy Flip"),
	HERCULES_ROCKTHROW = 149 UMETA(DisplayName = "Hercules Rock Throw"),
	HERCULES_ENERGYBURST = 150 UMETA(DisplayName = "Hercules Energy Burst"),
	WOODY_SHOULDERTACKLE = 151 UMETA(DisplayName = "Woody Shoulder Tackle"),
	WOODY_ROPEATTACK = 152 UMETA(DisplayName = "Woody Rope Attack"),
	BUZZ_BEAM = 153 UMETA(DisplayName = "Buzz Beam"),
	BUZZ_DOUBLELARIAT = 154 UMETA(DisplayName = "Buzz Double Lariat"),
	RAPUNZEL_HAIRSWING = 155 UMETA(DisplayName = "Rapunzel Hair Swing"),
	RAPUNZEL_HAIRROTATION = 156 UMETA(DisplayName = "Rapunzel Hair Rotation"),
	FLYNN_THROWFRYINGPAN = 157 UMETA(DisplayName = "Flynn Throw Frying Pan"),
	FLYNN_BARRELBASH = 158 UMETA(DisplayName = "Flynn Barrel Bash"),
	SULLEY_ROAR = 159 UMETA(DisplayName = "Sulley Roar"),
	SULLEY_SHOULDERTACKLE = 160 UMETA(DisplayName = "Sulley Shoulder Tackle"),
	MIKE_MIKEAPPEAL = 161 UMETA(DisplayName = "Mike Appeal"),
	MIKE_SUPPORT = 162 UMETA(DisplayName = "Mike Support"),
	SPARROW_BONECRASH = 163 UMETA(DisplayName = "Sparrow Bone Crash"),
	SPARROW_TWISTROLLING = 164 UMETA(DisplayName = "Sparrow Twist Rolling"),
	MARSHMALLOW_JUMPSTRIKE = 165 UMETA(DisplayName = "Marshmallow Jump Strike"),
	MARSHMALLOW_COLDBREATH = 166 UMETA(DisplayName = "Marshmallow Cold Breath"),
	BAYMAX_ROCKETPUNCH = 167 UMETA(DisplayName = "Baymax Rocket Punch"),
	BAYMAX_CURESPRAY = 168 UMETA(DisplayName = "Baymax Cure Spray"),
	RIKU_DARKFIRE = 169 UMETA(DisplayName = "Riku Dark Fire"),
	RIKU_SHADOWBREAKER = 170 UMETA(DisplayName = "Riku Shadow Breaker"),
	VENTUS_WINDRAID = 171 UMETA(DisplayName = "Ventus Wind Raid"),
	AQUA_BLIZZAGA = 172 UMETA(DisplayName = "Aqua Blizzaga"),
	AQUA_THUNDAGA = 173 UMETA(DisplayName = "Aqua Thundaga"),
	AQUA_CURAGA = 174 UMETA(DisplayName = "Aqua Curaga"),
	ROXAS_CROSSSHOT = 175 UMETA(DisplayName = "Roxas Cross Shot"),
	ROXAS_CROSSBRADE = 176 UMETA(DisplayName = "Roxas Cross Brade"),
	XION_CURAGA = 177 UMETA(DisplayName = "Xion Curaga"),
	XION_LASERRAIN = 178 UMETA(DisplayName = "Xion Laser Rain"),
	__LEA_FIRAGARAID = 179 UMETA(DisplayName = "Lea Firaga Raid"),
	LEA_FIRAGASLICER = 180 UMETA(DisplayName = "Lea Firaga Slicer"),
	KAIRI_CURE = 181 UMETA(DisplayName = "Kairi Cure"),
	SORA_FIRAGA = 182 UMETA(DisplayName = "Sora Firaga"),
	SORA_CURAGA = 183 UMETA(DisplayName = "Sora Curaga"),
    TRES_ABI_KIND_MAX UMETA(Hidden),
};

