#pragma once
#include "CoreMinimal.h"
#include "ETresGumiShipEnemyStateID.generated.h"

UENUM(BlueprintType)
enum class ETresGumiShipEnemyStateID : uint8 {
    BLANK_STATE,
    DEAD_STATE,
    APPEAR_STATE,
    DISAPPEAR_STATE,
    IDLING_STATE,
    CINEMATIC_MODE_STATE,
    FIELD_ENCOUNT_SYMBOL_STATE,
    ATTACK1_STATE,
    ATTACK2_STATE,
    ATTACK3_STATE,
    ATTACK4_STATE,
    ATTACK5_STATE,
    ATTACK6_STATE,
    ATTACK7_STATE,
    ATTACK8_STATE,
    ATTACK9_STATE,
    ATTACK10_STATE,
    ACTION1_STATE,
    ACTION2_STATE,
    ACTION3_STATE,
    ACTION4_STATE,
    ACTION5_STATE,
    ACTION6_STATE,
    ACTION7_STATE,
    SPECIAL1_STATE,
    SPECIAL2_STATE,
    SPECIAL3_STATE,
    SPECIAL4_STATE,
    SPECIAL5_STATE,
    SPECIAL6_STATE,
    SPECIAL7_STATE,
    STATE_ID_MAX UMETA(Hidden),
};

