#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefNavimap.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefNavimap : uint8 {
    NM_WCID_DW01,
    NM_WCID_DW02,
    NM_WCID_DW03,
    NM_WCID_DW04,
    NM_WCID_MI01,
    NM_WCID_MI02,
    NM_WCID_MI03,
    NM_WCID_MI04,
    NM_WCID_TS01,
    NM_WCID_TS02,
    NM_WCID_TS03,
    NM_WCID_TS04,
    NM_WCID_FZ01,
    NM_WCID_FZ02,
    NM_WCID_FZ03,
    NM_WCID_FZ04,
    NM_WCID_RA01,
    NM_WCID_RA02,
    NM_WCID_RA03,
    NM_WCID_RA04,
    NM_WCID_CA01,
    NM_WCID_CA02,
    NM_WCID_CA03,
    NM_WCID_CA04,
    NM_WCID_HE01,
    NM_WCID_HE02,
    NM_WCID_HE03,
    NM_WCID_HE04,
    NM_WCID_BX01,
    NM_WCID_BX02,
    NM_WCID_BX03,
    NM_WCID_BX04,
    NM_WCID_TT01,
    NM_WCID_TT02,
    NM_WCID_TT03,
    NM_WCID_TT04,
    NM_WCID_PO01,
    NM_WCID_PO02,
    NM_WCID_PO03,
    NM_WCID_PO04,
    NM_WCID_KG01,
    NM_WCID_KG02,
    NM_WCID_KG03,
    NM_WCID_KG04,
    NM_WCID_EW01,
    NM_WCID_EW02,
    NM_WCID_EW03,
    NM_WCID_EW04,
    NM_WCID_BT01,
    NM_WCID_BT02,
    NM_WCID_BT03,
    NM_WCID_BT04,
    NM_WCID_CA05,
    _MAX = 0x64,
};

