#pragma once
#include "CoreMinimal.h"
#include "ETresEffectAreaCode.generated.h"

UENUM(BlueprintType)
enum ETresEffectAreaCode {
    TRES_EFFECT_AREA_00,
    TRES_EFFECT_AREA_01,
    TRES_EFFECT_AREA_02,
    TRES_EFFECT_AREA_03,
    TRES_EFFECT_AREA_04,
    TRES_EFFECT_AREA_05,
    TRES_EFFECT_AREA_06,
    TRES_EFFECT_AREA_07,
    TRES_EFFECT_AREA_08,
    TRES_EFFECT_AREA_09,
    TRES_EFFECT_AREA_10,
    TRES_EFFECT_AREA_11,
    TRES_EFFECT_AREA_12,
    TRES_EFFECT_AREA_13,
    TRES_EFFECT_AREA_14,
    TRES_EFFECT_AREA_15,
    TRES_EFFECT_AREA_16,
    TRES_EFFECT_AREA_17,
    TRES_EFFECT_AREA_18,
    TRES_EFFECT_AREA_19,
    TRES_EFFECT_AREA_20,
    TRES_EFFECT_AREA_21,
    TRES_EFFECT_AREA_22,
    TRES_EFFECT_AREA_23,
    TRES_EFFECT_AREA_24,
    TRES_EFFECT_AREA_25,
    TRES_EFFECT_AREA_26,
    TRES_EFFECT_AREA_27,
    TRES_EFFECT_AREA_28,
    TRES_EFFECT_AREA_29,
    TRES_EFFECT_AREA_30,
    TRES_EFFECT_AREA_MAX UMETA(Hidden),
};

