#pragma once
#include "CoreMinimal.h"
#include "ETresCommandCategory.generated.h"

UENUM(BlueprintType)
enum ETresCommandCategory {
    TRES_CMD_CATEGORY_NONE,
    TRES_CMD_CATEGORY_MOVE,
    TRES_CMD_CATEGORY_FREERUN,
    TRES_CMD_CATEGORY_DODGE,
    TRES_CMD_CATEGORY_GUARD,
    TRES_CMD_CATEGORY_COUNTER,
    TRES_CMD_CATEGORY_FFMOVE,
    TRES_CMD_CATEGORY_FFATTACK,
    TRES_CMD_CATEGORY_ATTACK,
    TRES_CMD_CATEGORY_RUNATTACK,
    TRES_CMD_CATEGORY_JUMPCOMBO,
    TRES_CMD_CATEGORY_MAGIC,
    TRES_CMD_CATEGORY_ITEM,
    TRES_CMD_CATEGORY_ACCESS,
    TRES_CMD_CATEGORY_STYLE,
    TRES_CMD_CATEGORY_FINISH,
    TRES_CMD_CATEGORY_EXTRA,
    TRES_CMD_CATEGORY_ATTRACTION,
    TRES_CMD_CATEGORY_FRIEND,
    TRES_CMD_CATEGORY_DMAGIC,
    TRES_CMD_CATEGORY_SUMMON,
    TRES_CMD_CATEGORY_SHOOTFLOW,
    TRES_CMD_CATEGORY_ATHLETIC,
    TRES_CMD_CATEGORY_ABILITY,
    TRES_CMD_CATEGORY_PRIZE,
    TRES_CMD_CATEGORY_OTHER,
    TRES_CMD_CATEGORY_DEBUG,
    TRES_CMD_CATEGORY_SWITCH,
    TRES_CMD_CATEGORY_END,
    TRES_CMD_CATEGORY_MAX UMETA(Hidden),
};

