#pragma once
#include "CoreMinimal.h"
#include "ETresBPEM_BattleEventType.generated.h"

UENUM(BlueprintType)
enum class ETresBPEM_BattleEventType : uint8 {
    UNKNOWN,
    HIT_ATTACK_PLAYER,
    HIT_ATTACK_ENEMY,
    HIT_ATTACK_NOREACTION_PLAYER,
    HIT_ATTACK_NOREACTION_ENEMY,
    MISS_ATTACK_PLAYER,
    MISS_ATTACK_ENEMY,
    GUARD_ATTACK,
    IGNORE_TAKING_DAMAGE_PLAYER,
    IGNORE_TAKING_DAMAGE_ENEMY,
    RECOVERED_PLAYER,
    RECOVERED_FRIEND,
    FIREMAGIC_S,
    BEGIN_SHOOTFLOW,
    END_SHOOTFLOW,
    BEGIN_ATHLETICFLOW,
    END_ATHLETICFLOW,
    BEGIN_ATTRACTIONFLOW,
    END_ATTRACTIONFLOW,
    BEGIN_DISNEYMAGIC,
    END_DISNEYMAGIC,
    BEGIN_STYLECHANGE,
    END_STYLECHANGE,
    BEGIN_STYLEFINISH,
    END_STYLEFINISH,
    ETresBPEM_MAX UMETA(Hidden),
};

