#pragma once
#include "CoreMinimal.h"
#include "ETresEnemy_ex013_WatageMaterialType.generated.h"

UENUM(BlueprintType)
enum ETresEnemy_ex013_WatageMaterialType {
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_ALL,
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_HALF,
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_NONE,
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_NONE2,
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_NONE3,
    TRES_ENEMY_EX013_WATAGE_MATERIAL_TYPE_MAX UMETA(Hidden),
};

