#pragma once
#include "CoreMinimal.h"
#include "ETresReactorCommandID.generated.h"

UENUM(BlueprintType)
enum class ETresReactorCommandID : uint8 {
    TRES_RCID_UNKNOWN,
    TRES_RCID_SAVE,
    TRES_RCID_TALK,
    TRES_RCID_OPEN,
    TRES_RCID_CHECK,
    TRES_RCID_SHOP,
    TRES_RCID_RESCUE,
    TRES_RCID_VEHICLE,
    TRES_RCID_SHIP,
    TRES_RCID_PLANE,
    TRES_RCID_GETOFF,
    TRES_RCID_GIGAS_ELECTRO,
    TRES_RCID_RAILSLIDE,
    TRES_RCID_PLANEBOSS,
    TRES_RCID_ENEMYSHIP,
    TRES_RCID_TRICK,
    TRES_RCID_WATERPLAY,
    TRES_RCID_EXTENDHAND,
    TRES_RCID_PUDDING,
    TRES_RCID_MAILINGTO,
    TRES_RCID_ANS_ENDURE,
    TRES_RCID_ANS_CHALLENGE,
    TRES_RCID_ANS_MIXING,
    TRES_RCID_ANS_BUMPING,
    TRES_RCID_ANS_BELIEVE,
    TRES_RCID_ANS_ACCEPT,
    TRES_RCID_SWING,
    TRES_RCID_ANS_USUAL,
    TRES_RCID_ANS_EASY,
    TRES_RCID_ANS_CHALLENGING,
    TRES_RCID_CARDDRAW,
    _TRES_RCID_MAX UMETA(Hidden),
};

