#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefMaterial.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefMaterial : uint8 {
	NOTHING = 0 UMETA(DisplayName = "Nothing"),
	ITEM01 = 1 UMETA(DisplayName = "Blazing Shard"),
	ITEM02 = 2 UMETA(DisplayName = "Blazing Stone"),
	ITEM03 = 3 UMETA(DisplayName = "Blazing Gem"),
	ITEM04 = 4 UMETA(DisplayName = "Blazing Crystal"),
	ITEM05 = 5 UMETA(DisplayName = "Frost Shard"),
	ITEM06 = 6 UMETA(DisplayName = "Frost Stone"),
	ITEM07 = 7 UMETA(DisplayName = "Frost Gem"),
	ITEM08 = 8 UMETA(DisplayName = "Frost Crystal"),
	ITEM09 = 9 UMETA(DisplayName = "Lightning Shard"),
	ITEM10 = 10 UMETA(DisplayName = "Lightning Stone"),
	ITEM11 = 11 UMETA(DisplayName = "Lightning Gem"),
	ITEM12 = 12 UMETA(DisplayName = "Lightning Crystal"),
	ITEM13 = 13 UMETA(DisplayName = "Lucid Shard"),
	ITEM14 = 14 UMETA(DisplayName = "Lucid Stone"),
	ITEM15 = 15 UMETA(DisplayName = "Lucid Gem"),
	ITEM16 = 16 UMETA(DisplayName = "Lucid Crystal"),
	ITEM17 = 17 UMETA(DisplayName = "Pulsing Shard"),
	ITEM18 = 18 UMETA(DisplayName = "Pulsing Stone"),
	ITEM19 = 19 UMETA(DisplayName = "Pulsing Gem"),
	ITEM20 = 20 UMETA(DisplayName = "Pulsing Crystal"),
	ITEM21 = 21 UMETA(DisplayName = "Writhing Shard"),
	ITEM22 = 22 UMETA(DisplayName = "Writhing Stone"),
	ITEM23 = 23 UMETA(DisplayName = "Writhing Gem"),
	ITEM24 = 24 UMETA(DisplayName = "Writhing Crystal"),
	ITEM25 = 25 UMETA(DisplayName = "Betwixt Shard"),
	ITEM26 = 26 UMETA(DisplayName = "Betwixt Stone"),
	ITEM27 = 27 UMETA(DisplayName = "Betwixt Gem"),
	ITEM28 = 28 UMETA(DisplayName = "Betwixt Crystal"),
	ITEM29 = 29 UMETA(DisplayName = "Twilight Shard"),
	ITEM30 = 30 UMETA(DisplayName = "Twilight Stone"),
	ITEM31 = 31 UMETA(DisplayName = "Twilight Gem"),
	ITEM32 = 32 UMETA(DisplayName = "Twilight Crystal"),
	ITEM33 = 33 UMETA(DisplayName = "Mythril Shard"),
	ITEM34 = 34 UMETA(DisplayName = "Mythril Stone"),
	ITEM35 = 35 UMETA(DisplayName = "Mythril Gem"),
	ITEM36 = 36 UMETA(DisplayName = "Mythril Crystal"),
	ITEM37 = 37 UMETA(DisplayName = "Sinister Shard"),
	ITEM38 = 38 UMETA(DisplayName = "Sinister Stone"),
	ITEM39 = 39 UMETA(DisplayName = "Sinister Gem"),
	ITEM40 = 40 UMETA(DisplayName = "Sinister Crystal"),
	ITEM41 = 41 UMETA(DisplayName = "Soothing Shard"),
	ITEM42 = 42 UMETA(DisplayName = "Soothing Stone"),
	ITEM43 = 43 UMETA(DisplayName = "Soothing Gem"),
	ITEM44 = 44 UMETA(DisplayName = "Soothing Crystal"),
	ITEM45 = 45 UMETA(DisplayName = "Wellspring Shard"),
	ITEM46 = 46 UMETA(DisplayName = "Wellspring Stone"),
	ITEM47 = 47 UMETA(DisplayName = "Wellspring Gem"),
	ITEM48 = 48 UMETA(DisplayName = "Wellspring Crystal"),
	ITEM49 = 49 UMETA(DisplayName = "Hungry Shard"),
	ITEM50 = 50 UMETA(DisplayName = "Hungry Stone"),
	ITEM51 = 51 UMETA(DisplayName = "Hungry Gem"),
	ITEM52 = 52 UMETA(DisplayName = "Hungry Crystal"),
	ITEM53 = 53 UMETA(DisplayName = "Fluorite"),
	ITEM54 = 54 UMETA(DisplayName = "Damascus"),
	ITEM55 = 55 UMETA(DisplayName = "Adamantite"),
	ITEM56 = 56 UMETA(DisplayName = "Orichalcum"),
	ITEM57 = 57 UMETA(DisplayName = "Orichalcum+"),
	ITEM58 = 58 UMETA(DisplayName = "Electrum"),
	ITEM59 = 59 UMETA(DisplayName = "Evanescent Crystal"),
	ITEM60 = 60 UMETA(DisplayName = "Illusory Crystal"),
    _MAX = 0x64 UMETA(Hidden)
};

