#pragma once
#include "CoreMinimal.h"
#include "ETresNpcActionOnType.generated.h"

UENUM(BlueprintType)
enum ETresNpcActionOnType {
    TRES_NPC_AOT_NONE,
    TRES_NPC_AOT_APPEAL,
    TRES_NPC_AOT_COMICAL_BTL,
    TRES_NPC_AOT_ACTION_POINT_MOVE,
    TRES_NPC_AOT_ACTION_POINT_ARRIVAL,
    TRES_NPC_AOT_TALK_POINT_MOVE,
    TRES_NPC_AOT_TALK_POINT_WAIT,
    TRES_NPC_AOT_SNOWCOVERSWING_WAIT,
    TRES_NPC_AOT_GIMMICK_WAIT,
    TRES_NPC_AOT_MOTION_PLAY,
    TRES_NPC_AOT_HAIR_ACTION,
    TRES_NPC_AOT_HAIR_ACTION_END,
    TRES_NPC_AOT_PRECEDE_MOVEMENT,
    TRES_NPC_AOT_MAX UMETA(Hidden),
};

