#pragma once
#include "CoreMinimal.h"
#include "ETresActorSpecificActionID.generated.h"

UENUM(BlueprintType)
enum ETresActorSpecificActionID {
    TRES_ASA_BOSS_DIE,
    TRES_ASA_SATYR_SCRUM,
    TRES_ASA_SATYR_WARP,
    TRES_ASA_GOOFYSHOOT_TOWER,
    TRES_ASA_GOOFYSHOOT_TARUNVERSED,
    TRES_ASA_GOOFYSHOOT_GENERAL,
    TRES_ASA_TURTLEFROG_INHALE,
    TRES_ASA_TURTLEFROG_SPIT,
    TRES_ASA_DAVYJONES_DRAWINGTOSS,
    TRES_ASA_DAVYJONES_DRAWINGEND,
    TRES_ASA_TORNADO_INHALE_START,
    TRES_ASA_TORNADO_LAUNCH_START,
    TRES_ASA_TORNADO_LAUNCH_END,
    TRES_ASA_PLANEBOSS_SHAKEOFF_START,
    TRES_ASA_PLANEBOSS_SHAKEOFF_END,
    TRES_ASA_PLANEBOSS_TURNAROUND_START,
    TRES_ASA_E_EX027_EAT_BIND_START,
    TRES_ASA_E_EX027_EAT_BIND_END,
    TRES_ASA_E_EX027_BITE_BIND_START,
    TRES_ASA_E_EX027_BITE_BIND_END,
    TRES_ASA_E_EX054_JUMP_CHANGE_CAMERA,
    TRES_ASA_E_CA901_TENTACLE_SUMMONS_CAMERA,
    TRES_ASA_E_EX721_FLASH_CAMERA,
    TRES_ASA_E_CA404_BEFORE_STOLETRAP,
    TRES_ASA_E_CA404_EXEC_STOLETRAP,
    TRES_ASA_GUMISHIP_WORLD_SYMBOL_START,
    TRES_ASA_GUMISHIP_TRAVEL_POINT_START,
    TRES_ASA_GUMISHIP_FINISHED_BATTLE_WIPE_START,
    TRES_ASA_LEVLE_PRIZEBOX_FOOD_GET,
    TRES_ASA_MIRX_REPLICA_WARP_ATTACK_START,
    TRES_ASA_MIRX_REPLICA_WARP_ATTACK_END,
    TRES_ASA_MIRX_MICKEY_HOLY_SEAL_START,
    TRES_ASA_MIRX_MICKEY_HOLY_SEAL_END,
    TRES_ASA_MIRX_MICKEY_HIT_FINISH_ATTACK,
    TRES_ASA_MAX UMETA(Hidden),
};

