#pragma once
#include "CoreMinimal.h"
#include "ETresWeaponType.generated.h"

UENUM(BlueprintType)
enum ETresWeaponType {
    TRES_WEAPON_TYPE_NONE,
    TRES_WEAPON_TYPE_01,
    TRES_WEAPON_TYPE_03,
    TRES_WEAPON_TYPE_02,
    TRES_WEAPON_TYPE_04,
    TRES_WEAPON_TYPE_05,
    TRES_WEAPON_TYPE_10,
    TRES_WEAPON_TYPE_07,
    TRES_WEAPON_TYPE_08,
    TRES_WEAPON_TYPE_09,
    TRES_WEAPON_TYPE_06,
    TRES_WEAPON_TYPE_12,
    TRES_WEAPON_TYPE_11,
    TRES_WEAPON_TYPE_13,
    TRES_WEAPON_TYPE_14,
    TRES_WEAPON_TYPE_15,
    TRES_WEAPON_TYPE_16,
    TRES_WEAPON_TYPE_17,
    TRES_WEAPON_TYPE_18,
    TRES_WEAPON_TYPE_19,
    TRES_WEAPON_TYPE_MAX UMETA(Hidden),
};

