#pragma once
#include "CoreMinimal.h"
#include "ETresBadStatusType.generated.h"

UENUM(BlueprintType)
enum class ETresBadStatusType : uint8 {
    TRES_BADSTAT_NONE,
    TRES_BADSTAT_DEATH,
    TRES_BADSTAT_CATCH,
    TRES_BADSTAT_DRILL_BIND,
    TRES_BADSTAT_YO_BIND,
    TRES_BADSTAT_RALPH_BIND,
    TRES_BADSTAT_ENERGYBURST,
    TRES_BADSTAT_FREEZE,
    TRES_BADSTAT_STOP,
    TRES_BADSTAT_MAGNET,
    TRES_BADSTAT_DRAIN,
    TRES_BADSTAT_ASPIR,
    TRES_BADSTAT_STUN,
    TRES_BADSTAT_SNEEZE,
    TRES_BADSTAT_HONEY,
    TRES_BADSTAT_CLOUD,
    TRES_BADSTAT_DISCHARGE,
    TRES_BADSTAT_BURN,
    TRES_BADSTAT_HP_BREAK,
    TRES_BADSTAT_TIME_BREAK,
    TRES_BADSTAT_MAX UMETA(Hidden),
};

