#pragma once
#include "CoreMinimal.h"
#include "ETresEnemyToyKind.generated.h"

UENUM(BlueprintType)
enum ETresEnemyToyKind {
    TRES_ENEMY_TOY_KIND_UNKNOWN,
    TRES_ENEMY_TOY_KIND_MONSTER,
    TRES_ENEMY_TOY_KIND_ANGELICAMBER,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_PIGS,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_DOG,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_CAT,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_ELEPHANT,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_COW,
    TRES_ENEMY_TOY_KIND_BOUNCYPETS_FROG,
    TRES_ENEMY_TOY_KIND_PATCHWORKANIMALS_PANDA,
    TRES_ENEMY_TOY_KIND_PATCHWORKANIMALS_LION,
    TRES_ENEMY_TOY_KIND_ROBO_ELEPHANT,
    TRES_ENEMY_TOY_KIND_ROBO_FAN_WHITE,
    TRES_ENEMY_TOY_KIND_ROBO_FAN_BLUE,
    TRES_ENEMY_TOY_KIND_ROBO_FAN_GREEN,
    TRES_ENEMY_TOY_KIND_MAX UMETA(Hidden),
};

