#pragma once
#include "CoreMinimal.h"
#include "ETresItemDefWeapon.generated.h"

UENUM(BlueprintType)
enum class ETresItemDefWeapon : uint8 {
    WEP_NOEQUIP = 0 UMETA(DisplayName = "No Equip"),
	WEP_KEYBLADE00 = 1 UMETA(DisplayName = "Kingdom Key"),
	WEP_KEYBLADE02 = 2 UMETA(DisplayName = "Hero's Origin"),
	WEP_KEYBLADE01 = 3 UMETA(DisplayName = "Shooting Star"),
	WEP_KEYBLADE03 = 4 UMETA(DisplayName = "Favorite Deputy"),
	WEP_KEYBLADE04 = 5 UMETA(DisplayName = "Ever After"),
	WEP_KEYBLADE09 = 6 UMETA(DisplayName = "Happy Gear"),
	WEP_KEYBLADE06 = 7 UMETA(DisplayName = "Crystal Snow"),
	WEP_KEYBLADE07 = 8 UMETA(DisplayName = "Hunny Spout"),
	WEP_KEYBLADE08 = 9 UMETA(DisplayName = "Nano Gear"),
	WEP_KEYBLADE05 = 10 UMETA(DisplayName = "Wheel of Fate"),
	WEP_KEYBLADE11 = 11 UMETA(DisplayName = "Grand Chef"),
	WEP_KEYBLADE10 = 12 UMETA(DisplayName = "Classic Tone"),
	WEP_KEYBLADE12 = 13 UMETA(DisplayName = "Oathkeeper"),
	WEP_KEYBLADE13 = 14 UMETA(DisplayName = "Oblivion"),
	WEP_KEYBLADE14 = 15 UMETA(DisplayName = "Ultima Weapon"),
	WEP_KEYBLADE15 = 16 UMETA(DisplayName = "Elemental Encoder"),
	WEP_KEYBLADE16 = 17 UMETA(DisplayName = "Keyblade 16"),
	WEP_KEYBLADE17 = 18 UMETA(DisplayName = "Keyblade 17"),
	WEP_KEYBLADE18 = 19 UMETA(DisplayName = "Keyblade 18"),
	WEP_KEYBLADE19 = 20 UMETA(DisplayName = "Keyblade 19"),
	WEP_DONALD00 = 21 UMETA(DisplayName = "Donald 00"),
	WEP_DONALD01 = 22 UMETA(DisplayName = "Donald 01"),
	WEP_DONALD02 = 23 UMETA(DisplayName = "Donald 02"),
	WEP_DONALD03 = 24 UMETA(DisplayName = "Donald 03"),
	WEP_DONALD04 = 25 UMETA(DisplayName = "Donald 04"),
	WEP_DONALD05 = 26 UMETA(DisplayName = "Donald 05"),
	WEP_DONALD06 = 27 UMETA(DisplayName = "Donald 06"),
	WEP_DONALD07 = 28 UMETA(DisplayName = "Donald 07"),
	WEP_DONALD08 = 29 UMETA(DisplayName = "Donald 08"),
	WEP_DONALD09 = 30 UMETA(DisplayName = "Donald 09"),
	WEP_DONALD10 = 31 UMETA(DisplayName = "Donald 10"),
	WEP_DONALD11 = 32 UMETA(DisplayName = "Donald 11"),
	WEP_DONALD12 = 33 UMETA(DisplayName = "Donald 12"),
	WEP_DONALD13 = 34 UMETA(DisplayName = "Donald 13"),
	WEP_DONALD14 = 35 UMETA(DisplayName = "Donald 14"),
	WEP_DONALD15 = 36 UMETA(DisplayName = "Donald 15"),
	WEP_DONALD16 = 37 UMETA(DisplayName = "Donald 16"),
	WEP_DONALD17 = 38 UMETA(DisplayName = "Donald 17"),
	WEP_DONALD18 = 39 UMETA(DisplayName = "Donald 18"),
	WEP_DONALD19 = 40 UMETA(DisplayName = "Donald 19"),
	WEP_GOOFY00 = 41 UMETA(DisplayName = "Goofy 00"),
	WEP_GOOFY01 = 42 UMETA(DisplayName = "Goofy 01"),
	WEP_GOOFY02 = 43 UMETA(DisplayName = "Goofy 02"),
	WEP_GOOFY03 = 44 UMETA(DisplayName = "Goofy 03"),
	WEP_GOOFY04 = 45 UMETA(DisplayName = "Goofy 04"),
	WEP_GOOFY05 = 46 UMETA(DisplayName = "Goofy 05"),
	WEP_GOOFY06 = 47 UMETA(DisplayName = "Goofy 06"),
	WEP_GOOFY07 = 48 UMETA(DisplayName = "Goofy 07"),
	WEP_GOOFY08 = 49 UMETA(DisplayName = "Goofy 08"),
	WEP_GOOFY09 = 50 UMETA(DisplayName = "Goofy 09"),
	WEP_GOOFY10 = 51 UMETA(DisplayName = "Goofy 10"),
	WEP_GOOFY11 = 52 UMETA(DisplayName = "Goofy 11"),
	WEP_GOOFY12 = 53 UMETA(DisplayName = "Goofy 12"),
	WEP_GOOFY13 = 54 UMETA(DisplayName = "Goofy 13"),
	WEP_GOOFY14 = 55 UMETA(DisplayName = "Goofy 14"),
	WEP_GOOFY15 = 56 UMETA(DisplayName = "Goofy 15"),
	WEP_GOOFY16 = 57 UMETA(DisplayName = "Goofy 16"),
	WEP_GOOFY17 = 58 UMETA(DisplayName = "Goofy 17"),
	WEP_GOOFY18 = 59 UMETA(DisplayName = "Goofy 18"),
	WEP_GOOFY19 = 60 UMETA(DisplayName = "Goofy 19"),
	WEP_AQUA00 = 61 UMETA(DisplayName = "Aqua (Master's Defender)"),
	WEP_AQUA01 = 62 UMETA(DisplayName = "Aqua 01"),
	WEP_AQUA02 = 63 UMETA(DisplayName = "Aqua 02"),
	WEP_AQUA03 = 64 UMETA(DisplayName = "Aqua 03"),
	WEP_MICKEY00 = 65 UMETA(DisplayName = "Mickey 00"),
	WEP_MICKEY01 = 66 UMETA(DisplayName = "Mickey (Kingdom Key D)"),
	WEP_MICKEY02 = 67 UMETA(DisplayName = "Mickey (Star Cluster)"),
	WEP_MICKEY03 = 68 UMETA(DisplayName = "Mickey 03"),
	WEP_HERCULES00 = 69 UMETA(DisplayName = "Hercules 00"),
	WEP_WOODY00 = 70 UMETA(DisplayName = "Woody 00"),
	WEP_BUZZ00 = 71 UMETA(DisplayName = "Buzz 00"),
	WEP_RAPUNZEL00 = 72 UMETA(DisplayName = "Rapunzel 00"),
	WEP_FLYNN00 = 73 UMETA(DisplayName = "Flynn 00"),
	WEP_JACK_SPARROW00 = 74 UMETA(DisplayName = "Jack Sparrow 00"),
	WEP_MARSHMALLOW00 = 75 UMETA(DisplayName = "Marshmallow 00"),
	WEP_BAYMAX00 = 76 UMETA(DisplayName = "Baymax 00"),
	WEP_SULLEY00 = 77 UMETA(DisplayName = "Sulley 00"),
	WEP_MIKE00 = 78 UMETA(DisplayName = "Mike 00"),
	WEP_RIKU00 = 79 UMETA(DisplayName = "Riku (Braveheart)"),
	WEP_RIKU01 = 80 UMETA(DisplayName = "Riku (Way to the Dawn)"),
	WEP_RIKU02 = 81 UMETA(DisplayName = "Riku 02"),
	WEP_RIKU03 = 82 UMETA(DisplayName = "Riku 03"),
	WEP_KAIRI00 = 83 UMETA(DisplayName = "Kairi (Destiny's Embrace)"),
	WEP_LEA00 = 84 UMETA(DisplayName = "Lea (Flame Liberator)"),
	WEP_TERRA00 = 85 UMETA(DisplayName = "Terra (Earthshaker)"),
	WEP_VENTUS00 = 86 UMETA(DisplayName = "Ventus (Wayward Wind)"),
	WEP_ROXAS00 = 87 UMETA(DisplayName = "Roxas (Oathkeeper & Oblivion)"),
	WEP_XION00 = 88 UMETA(DisplayName = "Xion (Kingdom Key)"),
	WEP_FRD_SORA00 = 89 UMETA(DisplayName = "FRD Sora (Kingdom Key)"),
    _WEP_MAX = 0x64 UMETA(Hidden),
};

