#pragma once
#include "CoreMinimal.h"
#include "ETresMiRxReplicaManagerStateKind.generated.h"

UENUM(BlueprintType)
enum ETresMiRxReplicaManagerStateKind {
    STATE_KIND_IDLE,
    STATE_KIND_LASER_OMEN,
    STATE_KIND_SINGLE_LASER,
    STATE_KIND_FULL_FIRE_LASER,
    STATE_KIND_WARP_ATTACK,
    STATE_KIND_WARP_ATTACK_TWICE,
    STATE_KIND_WARP_ATTACK_THREE_TIMES,
    STATE_KIND_SLASER_AND_WARPATTACK_1,
    STATE_KIND_SLASER_AND_WARPATTACK_2,
    STATE_KIND_SLASER_AND_WARPATTACK_3,
    STATE_KIND_WARPATTACK_1_AND_SLASER,
    STATE_KIND_WARPATTACK_2_AND_SLASER,
    STATE_KIND_WARPATTACK_3_AND_SLASER,
    STATE_KIND_SIMULTANEOUT_WARPATTACK,
    STATE_KIND_WAIT,
    STATE_KIND_WAIT_CHANGE_IDLE,
    STATE_KIND_MAX UMETA(Hidden),
};

