#include "TresEnvQueryContext_PlayerFloorPositionFromNavmeshAndCollisionCheck.h"

UTresEnvQueryContext_PlayerFloorPositionFromNavmeshAndCollisionCheck::UTresEnvQueryContext_PlayerFloorPositionFromNavmeshAndCollisionCheck() {
}

